spring.datasource.url=jdbc:postgresql://db.upqwnzouwqnloghnnpqk.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=shrutidixit@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080